---
- hosts:
  become: yes
  tasks:
  - include_task: myfile.yml
  - name: install webserver
   apt:
    name: apache2
    state: present 

  - name: copy a test file to into node side
   copy:
    src: mytestfile
    dest: /home/cloud
    
   
