---
- hosts:
  become: yes
  tasks:
  - include_task: myfile.yml
  - name: install webserver
   apt:
    name: apache2
    state: present 

  - name: copy a test file to into node side
   copy:
    src: mytestfile
    dest: /home/cloud

  - name: download any internet file into node side 
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz
     dest:/home/cloud/apache-tomcat-10.0.20.tar.gz
    force_basic_auth: yes

   - name: copy index file into node side
     template:
     src: 
     dest: /var/html/index.html
      force_basic_auth: yes
