---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:  
    - name: i want to install webserver on ansible ubuntu
      apt:
       name: "{{mywebpackonubuntu}}"
       state: present
      when: ansible_os_family=="Debain"

    - name: i want to start webserver on ansible ubuntu node
      service:
       name: "{{mywebpackonubuntu}}"
       state: started
      when: ansible_os_family=="Debain"

    - name: i want to start webserver on ansible ubuntu node
      dnf:
       name: "{{mywebpackonredhat}}"
       state: started
      when: ansible_os_family=="Redhat"

    - name: i want to start webserver on ansible ubuntu node
      service:
       name: "{{mywebpackonredhat}}"
       state: started
      when: ansible_os_family=="Redhat"